<a href="https://colab.research.google.com/github/hamzaaitbourhim/PFE-HANDWRITTEN-DIGITS-RECOGNIZER/blob/main/HANDWRITTEN_DIGITS_RECOGNIZER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1- AND perceptron without using TensorFlow :**



In [ ]:
# importing numpy library 
import numpy

# define perceptron function
def perceptron(W, X):
  if numpy.dot(W, X) > 0:
    return 1
  else:
    return 0

# define learn function
def learn(W,X,Y):
  for i in range(Y.size):
    for j in range(W.size):
      W[j] = W[j] + 0.2*(Y[i] - perceptron(W,X[i]))*X[i,j]
    print("new parameters are : w0 = {}, w1 = {}, w2 = {}".format(W[0], W[1], W[2]))

# Parameters
W = numpy.array([0.8, -1, -1]) # w0,w1 and w2 are initialized to 0.8, -1, -1

# learning data x0 x1 x2 y
X = numpy.array([[1, 0, 0], [1, 1, 1], [1, 0, 1], [1, 1, 0]])
Y= numpy.array([0, 1, 0, 0])

#call learn
learn(W,X,Y)

new parameters are : w0 = 0.6000000000000001, w1 = -1.0, w2 = -1.0
new parameters are : w0 = 0.8, w1 = -0.8, w2 = -0.8
new parameters are : w0 = 0.8, w1 = -0.8, w2 = -0.8
new parameters are : w0 = 0.8, w1 = -0.8, w2 = -0.8


# **2- AND perceptron with TensorFlow :**

In [ ]:
#importing librairies
import numpy as np
import tensorflow as tf

#input set
x = np.array([ [1, 0, 0], [1, 1, 1], [1, 0, 1], [1, 1, 0] ])

#desired output
y = np.array([0, 1, 0, 0])

#weights
w = np.array([0.8, -1, -1])

print("\nWeights before learning: \n")
print(w)

#learning rate
n = 0.2

print("\nWeights during learning: \n")
#learning process
for i in range(len(y)):
        tmp = np.heaviside(tf.experimental.numpy.dot(x[i], w), 0)
        w += tf.subtract(y[i] - tmp , 0) * n * x[i]
        print(w)

print("\nWeights after learning: \n")
print(w)

print("\nDesired Output: \n")
print(y)

print("\nActual Output: \n")
np.heaviside(np.dot(x, w), 0)


Weights before learning: 

[ 0.8 -1.  -1. ]

Weights during learning: 

tf.Tensor([ 0.6 -1.  -1. ], shape=(3,), dtype=float64)
tf.Tensor([ 0.8 -0.8 -0.8], shape=(3,), dtype=float64)
tf.Tensor([ 0.8 -0.8 -0.8], shape=(3,), dtype=float64)
tf.Tensor([ 0.8 -0.8 -0.8], shape=(3,), dtype=float64)

Weights after learning: 

tf.Tensor([ 0.8 -0.8 -0.8], shape=(3,), dtype=float64)

Desired Output: 

[0 1 0 0]

Actual Output: 



array([1., 0., 0., 0.])